新增Too Many Requests和迁移至discord 2.X
SHELTER-ZONE/Discord_Bot_FAQ pull request #17
Opened 2022-08-27 19:55 UTC by AndyLonly

+discord.errors.HTTPException: 429 Too Many Requests
+从旧的dpy 1.X更新至dpy 2.X
    +Runtimewarning: coroutine 'bot.load_extension' was never awaited
    +xxxx missing 1 required keyword-only argument: 'intents' 或者对事件无反应
    +Webhook报错module 'discord' has no attribute xxxx

2022-09-02 06:51 UTC, Proladon requested changes

2022-09-02 06:51 UTC, Proladon commented on docs/python/index.md
> +## 从旧的dpy 1.X更新至dpy 2.X
我覺得這邊可以縮減成：
`從舊的 dpy 1.x 更新至 2.x`

2022-09-02 06:51 UTC, Proladon commented on docs/python/index.md
> +Intents列表:
這邊我覺得可以拿掉，或是貼一個 intents 的列表連結即可
主要是這邊只針對如何解決當前問題，其餘額外的相關設定簡明或是傳送門即可

2022-09-02 06:51 UTC, Proladon commented on docs/python/index.md
> +需要加载的Cog
這裡其實是不是能簡化成：
`load_extension()` 需加上 `await`
```py
await bot.load_extension()
```

---

主要是，會噴這個錯誤的都是原先不管用的是以下哪種情境的寫法
現在都是因為少了 `await` 才噴錯而已
或者目前各種情境code這邊 建議可以用
`<details> <summary>` 的形式折疊起來

2022-09-02 06:51 UTC, Proladon commented on docs/python/index.md
> +如果持续触发速率限制请做出以下调整
目前群內來詢問這個問題的好像大多是使用 repl.it 上遇到的
應該會需要補充針對 repl.it 的解決方案
不確定你知不知道 repl.it 的解決方案 ？ 
我是有點忘了 要查一下，好像是要在 repl 的終端用指令把 proccess kill 掉的樣子

2022-09-02 19:37 UTC, AndyLonly commented on docs/python/index.md
> +如果持续触发速率限制请做出以下调整
- 從舊的 dpy 1.x 更新至 2.x:heavy_check_mark:
- 這邊我覺得可以拿掉，或是貼一個 intents 的列表連結即可:heavy_check_mark:
- 這裡其實是不是能簡化成:heavy_check_mark:
- 目前群內來詢問這個問題的好像大多是使用 repl.it 上遇到的:x:

知道replit但从来没有用过，但理论上都是一样需要换个没被用烂的ip（大概）
需要协助 repl.it 的解決方案

2022-09-02 19:40 UTC, AndyLonly commented
0ad8dcf632bf5dae7e4d44927b38219a023d8548
- 從舊的 dpy 1.x 更新至 2.x:heavy_check_mark:
- 這邊我覺得可以拿掉，或是貼一個 intents 的列表連結即可:heavy_check_mark:
- 這裡其實是不是能簡化成:heavy_check_mark:
- 目前群內來詢問這個問題的好像大多是使用 repl.it 上遇到的:x:

知道replit但从来没有用过，但理论上都是一样需要换个没被用烂的ip（大概）
需要协助 repl.it 的解決方案

2022-09-03 13:08 UTC, Proladon commented
> [0ad8dcf](https://github.com/SHELTER-ZONE/Discord_Bot_FAQ/commit/0ad8dcf632bf5dae7e4d44927b38219a023d8548)
> 
> * 從舊的 dpy 1.x 更新至 2.x✔️
> * 這邊我覺得可以拿掉，或是貼一個 intents 的列表連結即可✔️
> * 這裡其實是不是能簡化成✔️
> * 目前群內來詢問這個問題的好像大多是使用 repl.it 上遇到的❌
> 
> 知道replit但从来没有用过，但理论上都是一样需要换个没被用烂的ip（大概） 需要协助 repl.it 的解決方案

repl.it的解法:
基本上就是在 repl.it 的終端輸入 `kill 1` 指令然後重啟
來源: 
https://replit.com/talk/ask/Discord-Bot-How-to-fix-429-rate-limit-error/121289

2022-09-03 18:01 UTC, AndyLonly commented
0e0577c
- 啊 原本那張 developer 哪張圖要留著✔️
- 基本上就是在 repl.it 的終端輸入 kill 1 指令然後重啟✔️

2022-09-09 06:49 UTC, merged