add: 有些在 cog 裡的指令偵測不到
SHELTER-ZONE/Discord_Bot_FAQ pull request #8
Opened 2022-05-25 11:47 UTC by a3510377

add: 有些在 cog 裡的指令偵測不到
for #2

2022-05-26 04:18 UTC, a3510377 commented
done

2022-05-26 15:12 UTC, Proladon requested changes

2022-05-27 11:28 UTC, a3510377 commented on docs/python/index.md
> +應該位於 class Task 中
done: [b174d48](https://github.com/SHELTER-ZONE/Discord_Bot_FAQ/pull/8/commits/b174d48b549d74eb0f11a7776ecb308ad7bae542)

2022-05-27 11:29 UTC, a3510377 commented
done

2022-05-28 13:23 UTC, Proladon approved these changes

2022-05-28 13:23 UTC, merged