add: xxxx is not a package
SHELTER-ZONE/Discord_Bot_FAQ pull request #9
Opened 2022-05-25 12:17 UTC by a3510377

add: xxxx is not a package
for #4

2022-05-26 04:18 UTC, a3510377 commented
done

2022-05-26 15:08 UTC, Proladon requested changes

2022-05-26 15:08 UTC, Proladon commented on docs/python/index.md
> +<div>執行 bot 後抱錯，找不到 discord 函數庫</div>
"抱"錯
報錯

2022-05-26 15:08 UTC, Proladon commented on docs/python/index.md
> +檔案/資料夾 命名與函數庫名稱相同
建議加個範例會比較好
有些小白可能連 `函數庫` / `函式庫` 是甚麼都不懂

例如:
```
原因：
檔案/資料夾 命名與函數庫名稱相同
例: 檔案名稱請勿命名為 discord.py
```

2022-05-27 10:25 UTC, a3510377 commented on docs/python/index.md
> +<div>執行 bot 後抱錯，找不到 discord 函數庫</div>
痾好尷尬ww

2022-05-27 10:25 UTC, a3510377 commented on docs/python/index.md
> +<div>執行 bot 後抱錯，找不到 discord 函數庫</div>
fix donw: https://github.com/SHELTER-ZONE/Discord_Bot_FAQ/pull/9/commits/fcdc6177e343200bffadd1412017234be1023dac

2022-05-27 10:47 UTC, a3510377 commented
done

2022-05-27 10:48 UTC, a3510377 commented on docs/python/index.md
> +檔案/資料夾 命名與函數庫名稱相同
fix: https://github.com/SHELTER-ZONE/Discord_Bot_FAQ/pull/9/commits/97423b7684886f083677e170b78760f7e2b5a58c

2022-05-28 13:26 UTC, Proladon approved these changes

2022-05-28 13:26 UTC, Proladon commented
@a3510377 有衝突，解一下

2022-05-29 03:18 UTC, a3510377 commented
done

2022-05-29 07:07 UTC, merged